sudo: false

language: c

addons:
  apt:
    packages:
    - ia32-libs
    - ia32-libs-multiarch
    
before_install:
 # Download the SDK
 - wget https://github.com/Metastruct/gtravis/releases/download/travisbins/gluac.tar.xz
 - tar -xf gluac.tar.xz
 - export LD_LIBRARY_PATH=`pwd`/gluac${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH:-}

 # Set the $PATH so gluac can be executed
 - export PATH=$PATH:`pwd`/gluac
 
 - echo $PWD

script: echo lua/test.lua | gluac
